[package]
name = "libsoma"
version = "0.0.1"
edition = "2024"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "libsoma"
path = "src/lib.rs"

[features]
max_rom_512b = [] # a tiny ROM for testing
max_rom_16kb = []
max_rom_32kb = []
max_rom_512kb = []

[dependencies]
psy = { path = "../../../psy/" }
