[package]
name = "soma"
version = "0.0.1"
edition = "2024"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[[bin]]
name = "soma"

[features]
web = []
desktop = []

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
eframe = "0.36.2"
egui = "0.36.2"
egui-phosphor = { version = "0.14", features = ["regular", "fill"] }

libsoma = { path = "../soma_lib", features = ["max_rom_512kb"] }
psy = { path = "../../../psy/" }
